# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"

install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version
  - npm install 

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # compile, lint and run tests
  - npm test

# Don't actually build.
build: off
